# Generated by Django 3.1.7 on 2021-03-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210331_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[('1/5', 'Boring'), ('2/5', 'Okay'), ('3/5', 'Fun'), ('4/5', 'Great'), ('5/5', 'Awesome')], default='1/5', max_length=3),
        ),
    ]
